"""Generate results/SUMMARY.md from whatever's in results/metrics/.

Run after training + evaluating + robustness-sweeping the models you
care about:

    python -m watkins.summarize

This is the CLI/reproducible counterpart to notebook 05's inline
comparison -- useful for regenerating the README-linked summary after a
fresh batch of runs without opening a notebook.
"""
from __future__ import annotations

import json

from .data import CLASS_IDS, CLASS_INFO
from .models import build_model
from .utils import count_parameters, results_root

KNOWN_RUNS = ["baseline_cnn", "resnet18", "efficientnet_b0", "ast_linear_probe"]
MODEL_KEY = {"baseline_cnn": "baseline_cnn", "resnet18": "resnet18",
             "efficientnet_b0": "efficientnet_b0", "ast_linear_probe": "ast"}
TOP_N_SPECIES = 15  # 54 columns doesn't fit a markdown table -- show the best-represented species


def _load_json(path):
    if not path.exists():
        return None
    with open(path) as f:
        return json.load(f)


def build_summary() -> str:
    metrics_dir = results_root() / "metrics"

    lines = ["# Results summary", "",
             "Auto-generated by `python -m watkins.summarize` from `results/metrics/`. "
             "See notebook 05 for the same comparison with plots.", ""]

    lines.append("## Headline comparison (54-species classification, tape-grouped split)")
    lines.append("")
    lines.append("| model | params | accuracy | macro F1 | weighted F1 |")
    lines.append("|---|---:|---:|---:|---:|")
    any_found = False
    first_metrics = None
    for run_name in KNOWN_RUNS:
        m = _load_json(metrics_dir / f"{run_name}_eval.json")
        if m is None:
            lines.append(f"| {run_name} | - | *not run yet* | | |")
            continue
        any_found = True
        first_metrics = first_metrics or m
        model, _ = build_model(MODEL_KEY[run_name], num_classes=len(CLASS_IDS))
        params = count_parameters(model)
        lines.append(f"| {run_name} | {params:,} | {m['accuracy']:.3f} | {m['macro_f1']:.3f} | {m['weighted_f1']:.3f} |")

    lines.append("")
    lines.append(f"## Per-class F1, top {TOP_N_SPECIES} best-represented species in the test set")
    lines.append("")
    if first_metrics is not None:
        # Drop sklearn's summary rows, not just some of them. When
        # classification_report gets an explicit `labels=`, it emits "micro avg"
        # in place of "accuracy" -- and its support is the whole split, so it
        # sorts to the top of a by-support ranking and steals a species slot.
        support = {name: rep["support"] for name, rep in first_metrics["report"].items()
                   if name != "accuracy" and not name.endswith(" avg")}
        top_species = [n for n, _ in sorted(support.items(), key=lambda kv: -kv[1])[:TOP_N_SPECIES]]
        lines.append("| model | " + " | ".join(top_species) + " |")
        lines.append("|---|" + "---:|" * len(top_species))
        for run_name in KNOWN_RUNS:
            m = _load_json(metrics_dir / f"{run_name}_eval.json")
            if m is None:
                continue
            row = [f"{m['report'][s]['f1-score']:.2f}" if s in m["report"] else "-" for s in top_species]
            lines.append(f"| {run_name} | " + " | ".join(row) + " |")
        lines.append("")
        lines.append("Full per-class report (all species) is in each "
                      "`results/metrics/<run_name>_eval.json`.")
    else:
        lines.append("*(no evaluated checkpoints yet)*")

    lines.append("")
    lines.append("## Robustness to noise (white noise, accuracy at each SNR)")
    lines.append("")
    import csv as _csv
    robustness_rows = {}
    snr_order = []
    for run_name in KNOWN_RUNS:
        path = metrics_dir / f"{run_name}_robustness.csv"
        if not path.exists():
            continue
        with open(path) as f:
            reader = _csv.DictReader(f)
            row_map = {}
            for row in reader:
                if row["noise_kind"] != "white" and row["snr_db"] != "inf":
                    continue
                snr = "clean" if row["snr_db"] == "inf" else f"{float(row['snr_db']):.0f}dB"
                row_map[snr] = float(row["accuracy"])
                if snr not in snr_order:
                    snr_order.append(snr)
            robustness_rows[run_name] = row_map
    if robustness_rows:
        lines.append("| model | " + " | ".join(snr_order) + " |")
        lines.append("|---|" + "---:|" * len(snr_order))
        for run_name, row_map in robustness_rows.items():
            row = [f"{row_map.get(s, float('nan')):.2f}" if s in row_map else "-" for s in snr_order]
            lines.append(f"| {run_name} | " + " | ".join(row) + " |")
    else:
        lines.append("*Run `python -m watkins.robustness --checkpoint ...` for each model "
                      "to populate this section.*")

    if not any_found:
        lines.append("")
        lines.append("*(No evaluated checkpoints found yet -- run the training configs in "
                      "`configs/` and then `python -m watkins.evaluate` / `python -m "
                      "watkins.robustness` on each checkpoint.)*")

    return "\n".join(lines) + "\n"


def _cli():
    out_path = results_root() / "SUMMARY.md"
    out_path.write_text(build_summary())
    print(f"wrote {out_path}")


if __name__ == "__main__":
    _cli()
